server:
  port: 4000

spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/boleto}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:solinftec}
    driver-class-name: org.postgresql.Driver

---
#jpa
spring:
  jpa:
    hibernate:
      ddl-auto: update # When you launch the application for the first time - switch "none" at "create"
    generate-ddl: true
#    show-sql: true
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    open-in-view: true


api:
  boleto: https://boleto.free.beeceptor.com/my/api/boleto
